container.image=azul/zulu-openjdk:8u492@sha256:185e7ab12b3706a39a56b2d5c8921f36ddff8e1c95d704a0a2f22b7e35c611d1
environment.LC_ALL=C.UTF-8
environment.TZ=UTC
file.encoding=UTF-8
gradle.version=8.12.1
java.runtime.version=1.8.0_492-b09
java.vendor=Azul Systems, Inc.
java.version=1.8.0_492
os.arch=amd64
os.name=Linux
